### ISSUE TITLE
Apply Wine Staging

### ISSUE THREAD

**Issue by Amarjit3** [fastrizwaan/flatpak-wine#10]
Hello,

Thank you for this Flatpak - it's brilliant!

I managed to build it successfully using your instructions but I have a programme that requires the Staging patches. How do I apply these patches when building (the 7.0 rc2 release)?

Thanks and kind regards.

**Comment by fastrizwaan** [comment]
you need 2 things by editing `flatpak-wine-template.yml` 

1st you need to add the patch files (here assests/patch1); remember to copy the patch1, patch2 to assets directory.

[at line ](https://github.com/fastrizwaan/flatpak-wine/blob/main/Others/wine-7.0-rc2/flatpak-wine-template.yml#L303#L306)

```
    sources:
      - type: archive
        url: WINE_SOURCE_URL
        sha512: WINE_SOURCE_SUM
```
to
``` 
    sources:
      - type: archive
        url: WINE_SOURCE_URL
        sha512: WINE_SOURCE_SUM

     - type: file
       path: assets/patch1
     - type: file
       path: assets/patch2

```

2nd 
patch the files before compiling; https://github.com/fastrizwaan/flatpak-wine/blob/main/Others/wine-7.0-rc2/flatpak-wine-template.yml#L239#L243

from this: 
```
    # 1. Build wine64
    - export CC=x86_64-unknown-linux-gnu-gcc  &&
      export CXX=x86_64-unknown-linux-gnu-g++ &&
      mkdir wine64-build && cd wine64-build   &&
      ../configure 
```
to
```
    # 1. Build wine64
    - export CC=x86_64-unknown-linux-gnu-gcc  &&
      export CXX=x86_64-unknown-linux-gnu-g++ &&
      patch -p1 < patch1  && 
      patch -p0 < patch2  && 
      mkdir wine64-build && cd wine64-build   &&
      ../configure 
```
